// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = "html, body {\r\n  height: 100%;\r\n}\r\n\r\nbody {\r\n  display: flex;\r\n  flex-direction: column;\r\n  font-family: 'Times New Roman', Times, serif;\r\n  color: slategray;\r\n}\r\n\r\n#app {\r\n  flex: 1 0 auto;\r\n}\r\n\r\nfooter {\r\n  text-align: center;\r\n  flex-shrink: 0;\r\n}\r\n\r\nsection {\r\n  display: flex;\r\n  justify-content: center;\r\n  flex-direction: column;\r\n  width: 50%;\r\n  margin-left: auto;\r\n  margin-right: auto;\r\n}\r\n\r\nheader {\r\n  font-family: 'Courier New', Courier, monospace;\r\n  font-weight: bolder;\r\n  color: black;\r\n}\r\n\r\nmain > header {\r\n  color: white;\r\n  background-color: black;\r\n  text-align: center;\r\n  font-size: xx-large;\r\n}\r\n\r\nsection > header {\r\n  text-align: center;\r\n  text-justify: newspaper;\r\n  font-size: x-large;\r\n}\r\n\r\n.avatar {\r\n  display: inline-flex;\r\n  justify-content: center;\r\n  padding: 1rem;\r\n  border-radius: 45%;\r\n  background-color: lavender;\r\n  margin: 1em;\r\n}\r\n\r\n.avatarSetter {\r\n  display: flex;\r\n  flex-direction: row;\r\n}\r\n.avatarInputs {\r\n  display: flex;\r\n  flex-direction: column;\r\n  align-items: flex-end;\r\n  justify-content: center;\r\n}\r\n\r\nul, summary {\r\n  list-style-type: none;\r\n}\r\n\r\nnav > ul {\r\n  display: flex;\r\n  flex-direction: row;\r\n  background-color: lavender;\r\n  justify-content: center;\r\n}\r\nnav > ul > li {\r\n  margin: 1em;\r\n}\r\n\r\na {\r\n  color: black;\r\n  text-decoration: none;\r\n  font-size: large;\r\n}\r\na:hover{\r\n  color:darkslateblue;\r\n}\r\ninput[type='submit'], input[type='button'] {\r\n  color: darkslateblue;\r\n  background-color: white;\r\n  border: 1px solid darkslateblue;\r\n  border-radius: 5%;\r\n}\r\ninput[type='submit']:hover, input[type='button']:hover {\r\n  color: white;\r\n  background-color: darkslateblue;\r\n}\r\n\r\n.category {\r\n  margin: 2em;\r\n}\r\n\r\n.subCategoryList {\r\n  display: flex;\r\n  flex-direction: row;\r\n  flex-wrap: wrap;\r\n}\r\n\r\n.subCategory {\r\n  flex: content;\r\n  display: inline-flex;\r\n  flex-direction: column;\r\n  align-items: center;\r\n  margin: 1em;\r\n  background-color: lavender;\r\n  border-radius: 5%;\r\n  border: 1px black dotted;\r\n  color: black;\r\n  padding: 1rem;\r\n}\r\n\r\n.preferencesCatList {\r\n  display: flex;\r\n  flex-direction: row;\r\n  flex-wrap: wrap;\r\n  justify-content: left;\r\n}\r\n.preferencesCatList > li {\r\n  margin-right: 1rem;\r\n  margin-bottom: 1rem;\r\n}\r\n\r\n.feedReader > article {\r\n  margin-bottom: 2em;\r\n  border: 1px dotted lavender;\r\n  padding: 1rem;\r\n}";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}